export const rows = [
  { 
    id: 1, 
    lastName: 'Snow', 
    firstName: 'Jon', 
    age: 35,
    gender: 'Male',
    course: 'Computer Science',
    fee: '£14000',
    score: '70%',
    country: 'England',
    level: 'MSc',
    status: 'Citizen',
    decision: 'Accepted',

  },
  { 
    id: 2, 
    lastName: 'Lannister', 
    firstName: 'Cersei', 
    age: 42,
    gender: 'Male',
    course: 'Computer Science',
    fee: '£14000',
    score: '70%',
    country: 'England',
    level: 'MSc',
    status: 'Citizen',
    decision: 'Accepted',

  },
  { 
    id: 3, 
    lastName: 'Lannister', 
    firstName: 'Jaime', 
    age: 45,
    gender: 'Male',
    course: 'Computer Science',
    fee: '£14000',
    score: '70%',
    country: 'England',
    level: 'MSc',
    status: 'Citizen',
    decision: 'Accepted',

  },
  { 
    id: 4, 
    lastName: 'Stark', 
    firstName: 'Arya', 
    age: 16,
    gender: 'Male',
    course: 'Computer Science',
    fee: '£14000',
    score: '70%',
    country: 'England',
    level: 'MSc',
    status: 'Citizen',
    decision: 'Accepted',

  },
  { 
    id: 5, 
    lastName: 'Targaryen', 
    firstName: 'Daenerys', 
    age: 25,
    gender: 'Male',
    course: 'Computer Science',
    fee: '£14000',
    score: '70%',
    country: 'England',
    level: 'MSc',
    status: 'Citizen',
    decision: 'Accepted',
    
  },
  { 
    id: 6, 
    lastName: 'Melisandre', 
    firstName: 'Matt', 
    age: 15,
    gender: 'Male',
    course: 'Computer Science',
    fee: '£14000',
    score: '70%',
    country: 'England',
    level: 'MSc',
    status: 'Citizen',
    decision: 'Accepted',

  },
  { 
    id: 7, 
    lastName: 'Clifford', 
    firstName: 'Ferrara', 
    age: 44,
    gender: 'Male',
    course: 'Computer Science',
    fee: '£14000',
    score: '70%',
    country: 'England',
    level: 'MSc',
    status: 'Citizen',
    decision: 'Accepted',

  },
  { 
    id: 8, 
    lastName: 'Frances', 
    firstName: 'Rossini', 
    age: 36,
    gender: 'Male',
    course: 'Computer Science',
    fee: '£14000',
    score: '70%',
    country: 'England',
    level: 'MSc',
    status: 'Citizen',
    decision: 'Accepted',

  },
  { 
    id: 9, 
    lastName: 'Roxie', 
    firstName: 'Harvey', 
    age: 65,
    gender: 'Male',
    course: 'Computer Science',
    fee: '£14000',
    score: '70%',
    country: 'England',
    level: 'MSc',
    status: 'Citizen',
    decision: 'Accepted',

  },
  { 
    id: 10, 
    lastName: 'Casey', 
    firstName: 'Paul', 
    age: 65,
    gender: 'Male',
    course: 'Computer Science',
    fee: '£14000',
    score: '70%',
    country: 'England',
    level: 'MSc',
    status: 'Citizen',
    decision: 'Accepted',

  },
];